### PR TITLE
Update code line reference

### PR DESCRIPTION
**Pull request by DanielSongShen**

### CODE REVIEW

**Review by nvasilakis — APPROVED** [review]
Thank you!

**Comment by nvasilakis** [comment]
(@dkarnikis The CI reports failing tests, and the details show something like `octokit` — would you have any idea why? Thanks!)

**Comment by dkarnikis** [comment]
@nvasilakis, I just issued a dummy ci test, and everything executed perfectly. 
I suppose that there might be an issue when merging/pushing code from other repos (e.g. @DanielSongShen's repo) to the main pash repo.

**Comment by nvasilakis** [comment]
Ah thanks!

**Pull request merged**
