### PR TITLE
nest tempfiles into a unique tempdir

### PR DESCRIPTION
**Pull request by kidd**
- This PR tries to unify all tmpfiles to live inside a unique directory.
- Some trailing whitespace cleaning
- runtime scripts are still outside the tempdir but I'm not sure it's that simple to move it without messing up :)

### CODE REVIEW

**Comment by angelhof** [comment]
Thanks a lot, this is a great change, going towards the right direction :)

I think we should use this PR to (1) also address #97 and (2) make sure that runtime output is also in this dir. This would allow for multi-user execution.

### Regarding (1):

The easiest way to go would be  to modify `pa.sh --init` (https://github.com/andromeda/pash/blob/main/pa.sh#L7) to create a directory `~/.pash/`. Then `pa.sh` could complain if that directory doesn't exist and it could ask for the user to run `pa.sh --init`. 

Then all of the temp files could be created in `~/.pash/temp/` (which should be a very easy change since you have gathered all logic for creating temp files in one place.

### Regarding (2):

At the moment the runtime creates temp files using `"$(mktemp --tmpdir -u pash_XXXXXXXXXX)"` (only used in `compiler/pash_runtime.sh` and `compiler/pash_runtime_quick_abort.sh` if I remember correctly). However, since we are going down that path, we could create a `pash_temp_file_name.sh` that calls your python code that gets a tempfile name and then use that in all places in the runtime to ensure that this logic is only in one place.

If you have time and are interested in doing these changes that would be great, otherwise I can look into them when I have some more time!

**Comment by kidd** [comment]
Hi! thanks for the feedback.

1. not sure the user wants to specifically run a step to initialize, if it's possible to run transparently.  in this case, the path is a conf. I'd say a sane approach is to default to that tempdir, that will effectively create a new directory on every run (which is cool for debugging purposes, if you add a condition to not rm it if `-d 1`). and if the user wants a particular one, then let him put it in a config.yaml (that I didn't implement). 

2. `man mktemp` says that if there's an env var TMPDIR, it'll use it. idk if this is too intrusive for what you want (not sure if the compiled scripts will want to have that overriden, but anyway, this only works when you don't specify any explicit dir in mktemp, so you usually don't care in those cases).

Feel free to merge and modify it to your needs.

**Comment by angelhof** [comment]
Thanks! I will take a look and apply my changes in the next couple days.

**Comment by angelhof** [comment]
I am closing this since it is subsumed by #116

**Pull request closed without merging**
