### PR TITLE
Use only Bash when summarizing performance test results

### PR DESCRIPTION
**Pull request by zyrolasting**
Make `ci-perf.sh` use only Bash. I also set `ci-perf.sh` so that you can either execute it, or source it. That proves helpful when one part of the script doesn't work and you need to iterate on that part.

Note that I verified this without running performance tests. I did this by iterating only on the `summarize_perf_suite` function. I don't expect this to be a problem because that's the only part of the code being replaced from the test runner's perspective.

Unblocks #139

### CODE REVIEW

**Comment by nvasilakis** [comment]
This looks good. Was that the only use of node for summarization? i.e., can we remove the node dependency from the docker file?

**Comment by zyrolasting** [comment]
@nvasilakis Yes. See #139

**Review by angelhof — APPROVED** [review]

**Review by nvasilakis — APPROVED** [review]
OK, let's merge and we can test!

**Comment by nvasilakis** [comment]
Instead of parsing all these times and converting to seconds, it would make sense to just have the scripts output in seconds.

**Pull request merged**
