### PR TITLE
Python Parsing

### PR DESCRIPTION
**Pull request by angelhof**
Replaces #145 so that it targets `future` instead.

### CODE REVIEW

**Comment by angelhof** [comment]
This is ready to merge, parsing and printing now goes straight through python (no fork/exec) and tests pass locally and on an EC2 instance. There are some cleaning issues that are left doing, but we can take care of them asynchronously in the future.

**Comment by thurstond** [comment]
Yay! Thanks @angelhof for all your git and Pash integration magic :-)

**Comment by angelhof** [comment]
@thurstond thanks for all those lines of c and python code :)

**Review by nvasilakis — APPROVED** [review]
Awesome!<3

**Pull request merged**
